name: algohive
services:
  # server:
  #   image: ghcr.io/eric-philippe/algohive/algohive/api:latest
  #   env_file: server.env
  #   depends_on:
  #     - db
  #     - cache
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - algohive-network

  # client:
  #   image: ghcr.io/eric-philippe/algohive/algohive/client:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - algohive-network

  beeapi-server1:
    container_name: beeapi-server-tlse
    image: ghcr.io/eric-philippe/algohive/beeapi:latest
    restart: unless-stopped
    volumes:
      - ./data/beeapi-server1/puzzles:/app/puzzles
    ports:
      - "5000:5000"
    networks:
      - algohive-network

  beeapi-server2:
    container_name: beeapi-server-mpl
    image: ghcr.io/eric-philippe/algohive/beeapi:latest
    restart: unless-stopped
    volumes:
      - ./data/beeapi-server2/puzzles:/app/puzzles
    ports:
      - "5001:5000"
    networks:
      - algohive-network

  db:
    container_name: algohive-db
    image: postgres:17-alpine
    env_file: server.env
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - algohive-network

  cache:
    container_name: algohive-cache
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - algohive-network

volumes:
  db-data:

networks:
  algohive-network:
