name: Build and Deploy HiveCraft Pip Package

on:
  push:
    branches:
      - main
    paths:
      - "hivecraft/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd hivecraft
          pip install build

      - name: Build package
        run: |
          cd hivecraft
          python -m build

      - name: Publish package to GitHub Packages
        run: |
          cd hivecraft
          # Set up authentication for GitHub Packages
          echo "__token__:${{ secrets.GITHUB_TOKEN }}" > ~/.pypirc
          # Publish to GitHub Packages
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
