name: Build and Deploy HiveCraft Pip Package

on:
  push:
    branches:
      - main
    paths:
      - "hivecraft/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd hivecraft
          pip install build

      - name: Build package
        run: |
          cd hivecraft
          python -m build
      - name: Rename wheel file
        run: |
          cd hivecraft/dist
          for file in *.whl; do
            mv "$file" "${file/none/${GITHUB_RUN_NUMBER}}"
          done

          for file in *.tar.gz; do
            mv "$file" "${file/none/${GITHUB_RUN_NUMBER}}"
          done

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hivecraft
          path: hivecraft/dist/*

      - name: Publish package to GitHub Packages
        run: |
          cd hivecraft
          python -m pip install --upgrade twine
          python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
