name: Build and Release CLI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # OS cible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --name hivecraft.exe hivecraft/run.py

      - name: Build executable (Linux)
        if: runner.os == 'Linux'
        run: pyinstaller --onefile --name hivecraft hivecraft/run.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ runner.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
